{% set version = "1.0.4" %}

package:
  name: divebomb
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/divebomb/divebomb-{{ version }}.tar.gz
  sha256: ad87786768b171d4a0d97e60513e7805e2fa99d6007c49bf1ad795ad1ebbe3ef

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pandas
    - numpy
    - sphinx
    - plotly
    - netcdf4
    - peakutils
    - scikit-learn
    - ipywidgets
    - xarray
    - colorlover

test:
  imports:
    - divebomb

about:
  home: https://gitlab.oceantrack.org/anunes/divebomb
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: 'An aquatic animal analysis tool for diving behaviour'
  description: |
    Divebomb is a python package that uses pandas
    to divide a timeseries of depths into individual
    dives and apply machine learning to cluster the
    dives.

  doc_url: http://divebomb.readthedocs.io/
  dev_url: https://gitlab.oceantrack.org/anunes/divebomb

extra:
  recipe-maintainers:
    - alexetnunes
