travis:
  secure:
    BINSTAR_TOKEN: MyYDgeEklzaeXpfNDeTbcyyi04RLMJHVOfh0mSKa9Gc8bmixJLz+cuwXFX2XH4hnxhTzLr14HZaMYGdUyoarr4xQ3eip/GQb/Z1+K/Un3099vZN+cbq2/VOBxMupOiahNtCSw8q2elN0jNHiMt3NsTutFRk1xGiIgQcM5YMLmFRx5RZDgGPgcEL47Ml8fsFSmLX0IpPwF/ZVIaa67xOFNeTcd8OaEXODJclYeXyIrEFslWV1NMQETH3DabUU+KiTqlzxrAdvDU/NMY7ELxhbQK2jP7fbiURs6NGUAr+Zii3CeWUCoZ7XGs+YfBdZ2lsKt8VOLD2RINkm0OobZvnegCYACIuJPv1PkgNQlNbDpN+dLxEnXSt8gJ8lGoe1iOB/rnTltxMhUTP1Djq966lXMrnJC1uQYJZtUB+1IslBCX7+qPwHi7ynoLc301ILL7+pH3P8nYdR/U84/74i9GSmwXfW317+smLnpBG7Md2JOHcM3gE9uTF2p0tt4JnGniubXtkhZqehpLevOHLB26DFUbGEty250DvtEKwTluDnWj86pIMMvJU34ontmi5FS19KZvpjM9b4IoPcSU2TgMFNns/v0uZUYwmiO7WFGni/J1qMm4rYvZ/I6cC2AKQTs9FSfrkZoAWngr6pWw0+TxDkIICfCnrnfOxNsZpU9BxP7EQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
